version: "3.4"
services:
  database_container:
    image: mysql
    container_name: "database_container"
    environment:
      - MYSQL_DATABASE=Movies
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=docker
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3018:3306"
    volumes:
      - "database_vol:/var/lib/mysql"
  dockertraining_daniel_perez:
    image: ${DOCKER_REGISTRY-}dockertraining_daniel_perez
    container_name: "api_container"
    build:
      context: .
      dockerfile: dockertraining_daniel_perez/Dockerfile
    ports:
      - "8091:80"
    environment:
      - ConnectionStrings:Movies=Server=database_container;Port=3306;Database=Movies; Uid=admin; Pwd=docker
    depends_on:
      - database_container
volumes:
  database_vol:
